// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5cHrEUMy2vW9iM0IIT7vBy4S7aItVvk',
    appId: '1:1063274841212:web:0fac2c3adae94be2d835f9',
    messagingSenderId: '1063274841212',
    projectId: 't-monument-448415-m3',
    authDomain: 't-monument-448415-m3.firebaseapp.com',
    storageBucket: 't-monument-448415-m3.firebasestorage.app',
    measurementId: 'G-G43KPVN4G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdgpQtdGcy1pA8TRL5PEO8ezN-vYdKT98',
    appId: '1:1063274841212:android:ed750cf1c33c379fd835f9',
    messagingSenderId: '1063274841212',
    projectId: 't-monument-448415-m3',
    storageBucket: 't-monument-448415-m3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3EZQxUq8z-6Do4N-5mlFVNnmMPZfcOPI',
    appId: '1:1063274841212:ios:ea446bbccd714b21d835f9',
    messagingSenderId: '1063274841212',
    projectId: 't-monument-448415-m3',
    storageBucket: 't-monument-448415-m3.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3EZQxUq8z-6Do4N-5mlFVNnmMPZfcOPI',
    appId: '1:1063274841212:ios:ea446bbccd714b21d835f9',
    messagingSenderId: '1063274841212',
    projectId: 't-monument-448415-m3',
    storageBucket: 't-monument-448415-m3.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM5cHrEUMy2vW9iM0IIT7vBy4S7aItVvk',
    appId: '1:1063274841212:web:92d3a25844d80926d835f9',
    messagingSenderId: '1063274841212',
    projectId: 't-monument-448415-m3',
    authDomain: 't-monument-448415-m3.firebaseapp.com',
    storageBucket: 't-monument-448415-m3.firebasestorage.app',
    measurementId: 'G-NH9J4M8PHZ',
  );
}
